### PR TITLE
Organize colors

### PR DESCRIPTION
**Pull request by michaelmccombie**
Sketch consumes the tokens sequentially and displays those colors across a row of 8 swatches. The way our color tokens are currently organized (by color) makes it difficult for a designer to find the color that they want with our Sketch palette.

This change would reorganize those color tokens making it easier for designers to work with in Sketch. 

One thing to note is that this change will make the protocol website a bit messy. So I will follow up this PR with a PR on that repo that sorts those colors alphabetically on that particular page. https://protocol.mozilla.org/fundamentals/color.html

Another thing to note is that some values (i.e. `color-pink-5`) are placed after the grayscale colors. This is intentional. Product requested more color weights than is needed by marketing so they are any value that occurs after the grayscale colors is hidden from Sketch's color picker.

image

### CODE REVIEW

**Comment by michaelmccombie** [comment]
@alexgibson I refactored this branch to create a seperate "colors-sketch.json" file to handle the Sketch specific formatting. 

This seemed like a way less convoluted way to organize our tokens for one specific platform

**Comment by michaelmccombie** [comment]
Resolves #40

**Comment by alexgibson** [comment]
@michaelmccombie this PR needs a rebase.

**Comment by craigcook** [comment]
We should still do this but it's an old PR and the tokens have changed. Closing this PR and we'll open a fresh one in its stead. Sorry for the neglect!

**Pull request closed without merging**
